# Generated by Django 2.0.2 on 2020-04-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_experience_app', '0006_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceitem',
            name='tag',
            field=models.TextField(default='activity'),
        ),
    ]
